# 参考: https://rust-lang.github.io/rustfmt
# 首先安装 nightly 的 toolchain
# rustup toolchain install nightly
# 然后在 clion 的 Language&Frameworks-Rust-Rustfmt 中设置 Channel 为 nightly
unstable_features = true

# 宽度
max_width = 120
comment_width = 120
chain_width = 120      # 链式语句的最大宽度
fn_call_width = 120   # 函数调用的最大宽度
fn_single_line = false
single_line_if_else_max_width = 120

# wrap_comments = true
format_strings = true
condense_wildcard_suffixes = true

# 大括号样式
brace_style = "AlwaysNextLine"

# 允许最大的空行数
blank_lines_upper_bound = 2

# 二元运算符的位置
binop_separator = "Back"

# import 相关
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true

# 换行符
newline_style = "Unix"
