[package]
name = "build-shader"
version = "0.1.0"
edition = "2021"
description = "手动编译 shader"


[dependencies]
truvis-crate-tools = { workspace = true }

log = { workspace = true }
chrono = { workspace = true }
env_logger = { workspace = true }
anstyle = { workspace = true }