[package]
name = "build-shader"
version = "0.1.0"
edition = "2021"


[dependencies]
log = { workspace = true }
chrono = { workspace = true }
env_logger = { workspace = true }
anstyle = { workspace = true }