[package]
name = "model-manager"
version = "0.1.0"
edition = "2021"


[dependencies]
truvis-rhi = { workspace = true }

ash = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
glam = { workspace = true, features = ["bytemuck", "rand", "serde"] }
