[package]
name = "vk-examples"
version = "0.1.0"
edition = "2021"


[dependencies]
truvis-render = { path = "../truvis-render" }

ash = { workspace = true }
memoffset = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
log = { workspace = true }


