[package]
name = "shader-toy"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { workspace = true }
memoffset = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
log = { workspace = true }


truvis-render = { path = "../truvis-render" }
