[package]
name = "truvis-shader-binding"
version = "0.1.0"
edition = "2024"
description = "通过 bindgen 生成 shader 对应的 rust 数据结构"


[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
glam = { workspace = true, features = ["bytemuck", "rand", "serde"] }


[build-dependencies]
bindgen = { workspace = true }