[package]
name = "shader-binding"
version = "0.1.0"
edition = "2021"


[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
glam = { workspace = true, features = ["bytemuck", "rand", "serde"] }


[build-dependencies]
bindgen = { workspace = true }