[package]
name = "shader-layout-macro"
version = "0.1.0"
edition = "2021"
description = "简化 shader binding"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
shader-layout-trait = { path = "../shader-layout-trait" }
